# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oqAPp3pr3gx5My1JZLzHaOj-4S5jqd6i
"""

import pandas as pd

df = pd.read_csv('sample_data/california_housing_train.csv')

df

"""Срез таблицы в data_df"""

data_df = df[df['population'] < 500]['median_house_value']

data_df

"""Задача 40: Cредняя стоимость дома, где кол-во людей от 0 до 500 (population) -> 206683.83635227982

"""

data_df.mean()

"""Задача 42: Узнать какая максимальная households в зоне минимального значения population -> 4"""

df[df['population'] == df['population'].min()]['households'].max()